### PR TITLE
Master

### PR DESCRIPTION
**Pull request by eusebe**
Add mathjax option to bsdoc.

### CODE REVIEW

**Comment by eusebe** [comment]
Implementing #87 (very basic integration of mathjax)

**Comment by davidgohel** [comment]
David

thanks for you help.

We just have to wait the travis output - if no problem, I will merge your work into the master branch

**Comment by davidgohel** [comment]
David 
Did you run R CMD CHECK? 

Something went wrong.

**Comment by eusebe** [comment]
Here what is returned:

```
library(devtools)
> check()
Updating ReporteRs documentation
Loading ReporteRs
Re-compiling ReporteRs
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL "D:\users\G-BCH-5053164\Documents\GitHub\ReporteRs"  \
  --library="d:\users\G-BCH-~1\AppData\Local\Temp\RtmpKGorvs\devtools_install_1f24167f2c97" --no-R --no-data --no-help --no-demo --no-inst --no-docs --no-exec  \
  --no-multiarch --no-test-load --preclean 

* installing *source* package 'ReporteRs' ...
** libs
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c DOCX.cpp -o DOCX.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c PPTX.cpp -o PPTX.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c RAPHAEL.cpp -o RAPHAEL.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c colors.cpp -o colors.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c common.cpp -o common.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c dml_utils.cpp -o dml_utils.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c raphael_utils.cpp -o raphael_utils.o
g++ -m64 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG     -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c utils.cpp -o utils.o
g++ -m64 -shared -s -static-libgcc -o ReporteRs.dll tmp.def DOCX.o PPTX.o RAPHAEL.o colors.o common.o dml_utils.o raphael_utils.o utils.o -Ld:/RCompile/r-compiling/local/local320/lib/x64 -Ld:/RCompile/r-compiling/local/local320/lib -LC:/PROGRA~1/R/R-32~1.2/bin/x64 -lR
installing to d:/users/G-BCH-~1/AppData/Local/Temp/RtmpKGorvs/devtools_install_1f24167f2c97/ReporteRs/libs/x64
* DONE (ReporteRs)
Loading required package: ReporteRsjars
Writing NAMESPACE
Writing addColumnBreak.Rd
Writing addDate.Rd
Writing addDocument.Rd
Writing addFlexTable.Rd
Writing addFooter.Rd
Writing addIframe.Rd
Writing addImage.Rd
Writing addMarkdown.Rd
Writing addPageBreak.Rd
Writing addPageNumber.Rd
Writing addParagraph.Rd
Writing addPlot.Rd
Writing addSection.Rd
Writing addSlide.Rd
Writing addSubtitle.Rd
Writing addRScript.Rd
Writing addCodeBlock.Rd
Writing addTitle.Rd
Writing toc.options.Rd
Writing addTOC.Rd
Writing chprop.Rd
Writing as.html.Rd
Writing as.FlexTable.Rd
Writing declareTitlesStyles.Rd
Writing slide.layouts.Rd
Writing styles.Rd
Writing writeDoc.Rd
Writing BootstrapMenu.Rd
Writing CodeBlock.Rd
Writing DropDownMenu.Rd
Writing FlexCell.Rd
Writing FlexRow.Rd
Writing FlexRow-alter.Rd
Writing FlexTable.Rd
Writing print.FlexTable.Rd
Writing addHeaderRow.Rd
Writing addFooterRow.Rd
Writing FlexTable-alter.Rd
Writing setFlexTableBorders.Rd
Writing setZebraStyle.Rd
Writing setRowsColors.Rd
Writing setColumnsColors.Rd
Writing setFlexTableBackgroundColors.Rd
Writing spanFlexTableRows.Rd
Writing spanFlexTableColumns.Rd
Writing setFlexTableWidths.Rd
Writing vanilla.table.Rd
Writing light.table.Rd
Writing FontMetric.Rd
Writing reporters_str_width.Rd
Writing Footnote.Rd
Writing addParagraph.Footnote.Rd
Writing print.Footnote.Rd
Writing doc-list-settings.Rd
Writing RScript.Rd
Writing as.html.RScript.Rd
Writing ReporteRs-package.Rd
Writing docx-bookmark.Rd
Writing addSection.docx.Rd
Writing addColumnBreak.docx.Rd
Writing add.plot.interactivity.Rd
Writing raphael_tracer_on.Rd
Writing raphael_tracer_off.Rd
Writing raphael_tooltips.Rd
Writing raphael_clicks.Rd
Writing raphael_dbclicks.Rd
Writing addBootstrapMenu.Rd
Writing addCodeBlock.bsdoc.Rd
Writing addCodeBlock.docx.Rd
Writing addCodeBlock.pptx.Rd
Writing addDate.pptx.Rd
Writing addDocument.docx.Rd
Writing addFlexTable.bsdoc.Rd
Writing addFlexTable.docx.Rd
Writing addFlexTable.pptx.Rd
Writing addFooter.bsdoc.Rd
Writing addFooter.pptx.Rd
Writing addIframe.bsdoc.Rd
Writing addImage.bsdoc.Rd
Writing addImage.docx.Rd
Writing addImage.pptx.Rd
Writing addLinkItem.Rd
Writing addMarkdown.bsdoc.Rd
Writing addMarkdown.docx.Rd
Writing addMarkdown.pptx.Rd
Writing addPageBreak.docx.Rd
Writing addPageNumber.pptx.Rd
Writing addParagraph.bsdoc.Rd
Writing addParagraph.docx.Rd
Writing addParagraph.pptx.Rd
Writing addPlot.bsdoc.Rd
Writing addPlot.docx.Rd
Writing addPlot.pptx.Rd
Writing addRScript.bsdoc.Rd
Writing addRScript.docx.Rd
Writing addRScript.pptx.Rd
Writing addSlide.pptx.Rd
Writing addSubtitle.pptx.Rd
Writing addTOC.bsdoc.Rd
Writing addTOC.docx.Rd
Writing addTitle.bsdoc.Rd
Writing addTitle.docx.Rd
Writing addTitle.pptx.Rd
Writing as.FlexTable.sessionInfo.Rd
Writing as.html.FlexTable.Rd
Writing borderProperties.Rd
Writing chprop.borderProperties.Rd
Writing bsdoc.Rd
Writing print.bsdoc.Rd
Writing addJavascript.Rd
Writing cellProperties.Rd
Writing chprop.cellProperties.Rd
Writing deleteBookmark.Rd
Writing deleteBookmarkNextContent.Rd
Writing dim.docx.Rd
Writing dim.pptx.Rd
Writing docx.Rd
Writing registerRaphaelGraph.Rd
Writing addPostCommand.Rd
Writing triggerPostCommand.Rd
Writing textNormal.Rd
Writing textBold.Rd
Writing textItalic.Rd
Writing textBoldItalic.Rd
Writing parRight.Rd
Writing parLeft.Rd
Writing parCenter.Rd
Writing parJustify.Rd
Writing borderDotted.Rd
Writing borderDashed.Rd
Writing borderNone.Rd
Writing borderSolid.Rd
Writing is.color.Rd
Writing parProperties.Rd
Writing chprop.parProperties.Rd
Writing pot.Rd
Writing pot_img.Rd
Writing print.pot.Rd
Writing plus-.pot.Rd
Writing as.html.pot.Rd
Writing pptx.Rd
Writing print.docx.Rd
Writing print.pptx.Rd
Writing raphael.html.Rd
Writing declareTitlesStyles.docx.Rd
Writing set_of_paragraphs.Rd
Writing add.pot.Rd
Writing slide.layouts.pptx.Rd
Writing styles.docx.Rd
Writing textProperties.Rd
Writing print.textProperties.Rd
Writing chprop.textProperties.Rd
Writing text_extract.Rd
Writing list_bookmarks.Rd
Writing toc.options.docx.Rd
Writing writeDoc.bsdoc.Rd
Writing as.html.bsdoc.Rd
Writing writeDoc.docx.Rd
Writing writeDoc.pptx.Rd
Setting env vars ---------------------------------------------------------------------------------------------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building ReporteRs -------------------------------------------------------------------------------------------------------------------------------------------------
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD build "D:\users\G-BCH-5053164\Documents\GitHub\ReporteRs"  \
  --no-resave-data --no-manual 

* checking for file 'D:\users\G-BCH-5053164\Documents\GitHub\ReporteRs/DESCRIPTION' ... OK
* preparing 'ReporteRs':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'ReporteRs_0.8.3.tar.gz'

Setting env vars ---------------------------------------------------------------------------------------------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking ReporteRs -------------------------------------------------------------------------------------------------------------------------------------------------
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD check  \
  "d:\users\G-BCH-~1\AppData\Local\Temp\RtmpKGorvs/ReporteRs_0.8.3.tar.gz" --as-cran --timings 

* using log directory 'd:/users/G-BCH-~1/AppData/Local/Temp/RtmpKGorvs/ReporteRs.Rcheck'
* using R version 3.2.2 (2015-08-14)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using option '--as-cran'
* checking for file 'ReporteRs/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'ReporteRs' version '0.8.3'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'ReporteRs' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ...
** running examples for arch 'i386' ... OK
Examples with CPU or elapsed time > 5s
         user system elapsed
Footnote 3.71   1.15    6.41
** running examples for arch 'x64' ... OK
Examples with CPU or elapsed time > 5s
         user system elapsed
Footnote 7.46   1.15    7.64
* checking PDF version of manual ... OK
* DONE

Status: OK
```

**Comment by davidgohel** [comment]
OK

I am wondering why both AppVeyor and Travis CI failed.

**Comment by eusebe** [comment]
I don't know these tools, sorry.
I really don't see where is the problem with this commit, but will check again tomorrow.

**Comment by davidgohel** [comment]
Hi

This is something to do with Travis ci and Mac os architecture (with java...).
I will see that later.

**Comment by eusebe** [comment]
I rerun `check()' with no error on my local machine, and I have no uncommited changes pending. 
github

I don't see anything in my changes that could explain these errors. I am really sorry if I missed something.
My sessionInfo:
```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252 LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.9.1 httr_1.0.0    

loaded via a namespace (and not attached):
[1] DYM_0.1.1      R6_2.1.1       magrittr_1.5   tools_3.2.2    memoise_0.2.1  stringi_0.5-5  digest_0.6.8   stringr_1.0.0  fortunes_1.5-2
```

**Comment by davidgohel** [comment]
Yes, it's ok, the issue occurred not because of your code but because of the java installation. 
I merged your pull request in the master branch.

**Pull request merged**
